name: Radio4U
main: io.github.lazoyoung.radio4u.spigot.Radio4Spigot
version: 1.0.1
author: LazoYoung
description: A Noteblock music player
depend: [NoteBlockAPI]

commands:
  playlist:
    description: Manage nbs music playlists.
    aliases: [musiclist]
    usage: Invalid command. Type /<command> to see help.
  radio:
    description: Play songs in a radio channel.
    aliases: [musicplayer, play]
    usage: Invalid command. Type /<command> to see help.
