name: Radio4U
main: io.github.lazoyoung.radio4u.spigot.Radio4Spigot
version: 1.1
author: LazoYoung
description: A Noteblock music player
depend: [NoteBlockAPI]
api-version: 1.13

commands:
  radio4u:
    description: Main command
    aliases: [radioplugin, radioplayer, musicplugin, musicplayer]
    usage: Invalid command. Type /<command> to see help.
  playlist:
    description: Manage nbs music playlists.
    usage: Invalid command. Type /<command> to see help.
  radio:
    description: Play songs in a radio channel.
    aliases: [musicplayer]
    usage: Invalid command. Type /<command> to see help.