name: Radio4U
main: io.github.lazoyoung.radio4u.spigot.Radio4Spigot
version: 1.0
author: LazoYoung
description: A Noteblock music player
depend: [NoteBlockAPI]

commands:
  song:
    description: Register nbs songs into this plugin.
    aliases: [music]
    usage: Invalid command. Type /<command> to see help.
  playlist:
    description: Manage nbs music playlists.
    aliases: [musiclist]
    usage: Invalid command. Type /<command> to see help.
  radio:
    description: Play songs in a radio channel.
    aliases: [musicplayer, play]
    usage: Invalid command. Type /<command> to see help.
